

language: python
env:
  - DJANGO_VERSION=1.4.10
  - DJANGO_VERSION=1.5.5
  - DJANGO_VERSION=1.6.2
python:
  - "2.6"
  - "2.7"
  - "3.3"
matrix:
  exclude:
     - python: "3.3"
       env: DJANGO_VERSION=1.4.10
install: pip install . --use-mirrors
script: ./forms_builder/example_project/manage.py test
